#page title
page_title: MagicRetouch # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6447635159 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.jpg # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: MagicRetouch # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Effortless Object Removal, Just a Tap # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Remove the Unwanted,  Rediscover Picture-Perfect Moments.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: CyberCat
your_link:
your_city:
email_address: cybercat.ai@gmail.com
facebook_username:
instagram_username:
twitter_username: zubin_tang
github_username: magic-retouch
youtube_username:
mastodon_link:

# Feature List
# Edit, add or remove features to be presented.
features:
  - title: Smart Selection
    description: Say goodbye to clunky erasers! Snap Eraser, powered by CAT (Cut-Anything-Tech), effortlessly identifies and circles objects with just a tap.
    fontawesome_icon_name: fas fa-magic

  - title: Enchanted Erasing
    description: Snap Eraser’s AI technology analyzes your photo, predicts and restores the missing parts. Only the most authentic repair can match your perfect shot.
    fontawesome_icon_name: fas fa-eraser

  - title: Lossless Editing
    description: Preserve the essence of your photography. Snap Eraser ensures lossless editing, respecting the art by maintaining quality and EXIF information.
    fontawesome_icon_name: fas fa-camera-retro

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
